config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  devise_for :users
  resources :categories,:articles,:comments,:cart_line_items

  root 'articles#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	validates_presence_of :name
	has_many :articles
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.all
		#puts "Category====>#{categories.inspect}"
	end
	def new
		@category = Category.new
    @comment = Comment.new
	end

	def create
		@category = Category.new(params[:category].permit(:name))
		#puts "new =======>#{@category}"
		if @category.save
			redirect_to categories_path,notice:"Successfully created Record #{@category.name}"
		else
			render action:new
		end
  end

  def show

     @category = Category.find(params[:id])
     @article = Article.where('category_id = ?',@category.id)
     if @article.empty?
      redirect_to categories_path ,notice:"Record not found"
    end
  end

  def edit
  	@category = Category.find(params[:id])
  end

  def update
  	@category = Category.find(params[:id])
    if @category.update_attributes(params[:category].permit(:name))
    	redirect_to categories_path(@category.id) , notice:"Successfully updated Record"
    else
    	render action: "edit" 
    end   
  end
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end
  
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h2> Editing form </h2>

<%= form_for @category do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %></br> </br>
	<%= f.submit %>

<% end %>
<%= link_to "Back",category_path(@category.id) %>

app/views/categories/index.html.erb
<h2> Listing Category: <%= @categories.length %> </h2>
<ol>
<% @categories.each do |category| %>
<li> <%= link_to category.name ,category_path(category.id)%> 
(<%= Article.where('category_id = ?',category.id).length %>)
<%#= link_to "show",category_path(category.id) %>
</li>
<% end %>
</ol>


<%= link_to "Add New Category",new_category_path,class: "btn btn-primary"%>

app/views/categories/new.html.erb
<h2> creating form </h2>
<%= form_for @category do |f| %>
<%= f.label :name %>
<%= f.text_field :name %></br> </br>
<%= f.submit %>

<% end %>
</br>
<%= link_to "Cancel",categories_path %>

app/views/categories/show.html.erb
<%= @category.name %>

<%= link_to "Edit", edit_category_path(@category.id)%>
<%= link_to "Destroy",category_path(@category.id),method: :delete, data: {confirm:"Are you sure"} %> :
<%# articles = Article.where('category_id = ?',@category.id) %>

<% if @article.empty? %>
	<p> Record  not found </p>
	<% else %>
<ol>
<% @article.each do |article| %>
<li>  <%= link_to article.title,article_path(article.id) %> - published on - <%= article.publish_date %> </li>
<% end %>
</ol>
<% end %>

<%= link_to "Back",categories_path %>